### ISSUE TITLE
Nav Bar messed up at 1000 width

### ISSUE THREAD

**Issue by RohitNagraj** [RohitNagraj/DSC-Website#12]
![screenshot from 2019-02-09 09-39-15](https://user-images.githubusercontent.com/41142333/52516309-94618100-2c4e-11e9-8d9a-ef59f5edff76.png)

**Comment by ishank-dev** [comment]
those two buttons are contained in a form tag thats why the signup button changes the row.
will fix it

**Comment by ishank-dev** [comment]
fixed
